title: HAssan Rahnama's CV
description:  Resume
#url: http://h_rahanama.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
